server:
  port: 5003

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://localhost:8080/


backing-services:
    case:
      base-uri: http://localhost:5000
    geo-data:
      base-uri: http://localhost:8087


