spring:
  application:
    name: network-conversion-server

  cloud:
    function:
      definition: consumeCaseImportStart
    stream:
      bindings:
        publishCaseImportStart-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
        publishCaseImportSucceeded-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
        publishCaseImportFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.failed
        consumeCaseImportStart-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
          group: importGroup
          consumer:
            concurrency: 2
      output-bindings: publishCaseImportStart;publishCaseImportSucceeded;publishCaseImportFailed

backing-services:
  network-store-server:
    preloading-strategy: COLLECTION

management:
  health:
    solr:
      enabled: false
