spring:
  application:
    name: network-conversion-server

  cloud:
    function:
      definition: consumeCaseImportStart
    stream:
      bindings:
        publishCaseImportStart-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
        publishCaseImportSucceeded-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
        consumeCaseImportStart-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
          group: importGroup
          consumer:
            concurrency: 2
            max-attempts: 1
      output-bindings: publishCaseImportStart-out-0;publishCaseImportSucceeded-out-0
      rabbit:
        bindings:
          consumeRun-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

management:
  health:
    solr:
      enabled: false
