spring:
  application:
    name: network-conversion-server

  cloud:
    function:
      definition: consumeCaseImportStart1;consumeCaseImportStart2;consumeNetworkExportStart1;consumeNetworkExportStart2;consumeCaseExportStart1;consumeCaseExportStart2
    stream:
      bindings:
        publishCaseImportStart-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
        publishCaseImportSucceeded-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
        # pay attention to max-concurrent-import-export parameter
        consumeCaseImportStart1-in-0: &consumeCaseImportStartConfig
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start
          group: importGroup
          consumer:
            max-attempts: 1
        consumeCaseImportStart2-in-0:
          <<: *consumeCaseImportStartConfig
        publishNetworkExportStart-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.start
        publishNetworkExportFinished-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.finished
        consumeNetworkExportStart1-in-0: &consumeNetworkExportStartConfig
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.start
          group: exportNetworkGroup
          consumer:
            max-attempts: 1
        consumeNetworkExportStart2-in-0:
          <<: *consumeNetworkExportStartConfig
        publishCaseExportStart-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.export.start
        publishCaseExportFinished-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.export.finished
        consumeCaseExportStart1-in-0: &consumeCaseExportStartConfig
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.export.start
          group: exportCaseGroup
          consumer:
            max-attempts: 1
        consumeCaseExportStart2-in-0:
          <<: *consumeCaseExportStartConfig
      output-bindings: publishCaseImportStart-out-0;publishCaseImportSucceeded-out-0;publishNetworkExportStart-out-0;publishNetworkExportFinished-out-0;publishCaseExportStart-out-0;publishCaseExportFinished-out-0
      rabbit:
        bindings:
          consumeCaseImportStart1-in-0: &consumeCaseImportStartRabbitConfig
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2
          consumeCaseImportStart2-in-0:
            <<: *consumeCaseImportStartRabbitConfig
          consumeNetworkExportStart1-in-0: &consumeNetworkExportStartRabbitConfig
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.start.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.start.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2
          consumeNetworkExportStart2-in-0:
            <<: *consumeNetworkExportStartRabbitConfig
          consumeCaseExportStart1-in-0: &consumeCaseExportStartRabbitConfig
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}case.export.start.dlx
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}case.export.start.dlx.dlq
              dead-letter-exchange-type: topic
              quorum:
                enabled: true
                delivery-limit: 2
          consumeCaseExportStart2-in-0:
            <<: *consumeCaseExportStartRabbitConfig

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

management:
  health:
    solr:
      enabled: false

export-subpath: "network_exports"

# maximum concurrent network import/export
# to avoid out of memory issues
# WARNING: pay attention for imports, that spring.cloud.stream.bindings.consumeCaseImportStart-in-0.consumer.concurrency
# is consistent with this parameter value
max-concurrent-import-export: 2
